name: dbt_translate CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  sqlmesh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install SQLMesh
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-duckdb
      - name: compile to check target
        run: |
          dbt compile
      - name: Upload compiled SQL
        uses: actions/upload-artifact@v4
        with:
          name: dbt-compiled
          path: target/compiled
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          path: target/compiled
      - name: Display structure of downloaded files
        run: ls -R path/to/artifacts
      - name: translate run
        run: python translate.py "${{ github.workspace }}/target/compiled"
      - name: Upload Translated SQL
        uses: actions/upload-artifact@v4
        with:
          name: dbt-compiled
          path: spark-update
      - name: Unzip and Update Repository Content
        uses: moehami/unzip-and-update-action@Unzip
        with:
          zip_file_path: "${{ github.workspace }}/target/compiled"

        
